FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at the working directory (/usr/src/app)
COPY . .

# Update packages and ensure cv2 runs
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip discord.py:2.5.0 install discord-py-slash-command:3.0.3

# Run main.py when the container launches
CMD ["python", "./main.py"]